# Alembic Configuration File

# The location of the migration files
script_location = migrations

# The SQLAlchemy connection string.
sqlalchemy.url = sqlite:///./horse_races.db

# The encoding of files to use.
file_encoding = utf-8

# A Python logging.config fileConfig() call to configure logging.
[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
